# This is a basic workflow that is manually triggered to update the mame libretro core

name: Libretro Mame core update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.  We do this in order to make sure to get update notes.
on:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job.
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Time to pull the proper branch of the watchnixtoons2 repo to start the plugin update
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
    - name: Build newest mame libretro core
      id: build_mame
      shell: bash {0}
      run: |
        sudo apt -y update
        sudo apt -y install build-essential git libarchive-zip-perl rsync zip
        git clone https://github.com/libretro/mame.git
        cd mame/
        make -f Makefile.libretro clean
        make SUBTARGET=arcade -f Makefile.libretro
        strip mamearcade_libretro.so
        mkdir -v ../cores64
        cp mamearcade_libretro.so ../cores64/mame_libretro.so
        
        gitcommit=$(git log | grep -m 1 commit | cut -c -14 | cut -c 8-)
        echo $gitcommit > ../cores64/mame_libretro.so.commit
        
        # Setup and commit plugin and updated addon.xml
        # git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # git config --local user.name "github-actions[bot]"
        # git add plugin.video.watchnixtoons2${branch}-${new_version}.zip addon.xml
        # git commit -m "Add plugin.video.watchnixtoons2${branch}-${new_version}.zip to repo"
        
        cd ..
        

    - name: Push new watchnixtoons2 premium kodi plugin version to plugin repo
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref_name }}

    # Both the watchnixtoons2 repo and ch.repo repo need to have the same secret token set or the push willl fail
    - name: checkout_chrepo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CHREPO_TOKEN }}
        repository: christianhaitian/ch.repo
        ref: master
        persist-credentials: true
        fetch-depth: 0

    - name: Add updated plugin to ch.repo
      id: build_repo
      shell: bash {0}
      run: |

        # Setting the new version of the addon here
        if [[ "$branch" == *"test"* ]]; then
          branchtest=""
        else
          branchtest="$branch"
        fi

        # Setting the new version of the addon here and adding change notes from input
        sed -i "/toons2$branchtest\" name\=\"WatchNixtoons2\" version\=\"/c\<addon id\=\"plugin.video.watchnixtoons2$branchtest\" name\=\"WatchNixtoons2\" version\=\"$new_version\" provider-name\=\"doko\/Christian-Haitian\">" addons.xml 
        sed -i "/\[B\]$cur_version\[\/B\]/s//\[B\]$new_version\[\/B\]\n\n\[B\]$cur_version\[\/B\]/" addons.xml
        notes=( "${{ github.event.inputs.change_note5 }}" "${{ github.event.inputs.change_note4 }}" "${{ github.event.inputs.change_note3 }}" "${{ github.event.inputs.change_note2 }}" "${{ github.event.inputs.change_note1 }}" )
        for note in "${notes[@]}"
        do
          if [ ! -z "$note" ]; then
            sed -i "s+\[B\]$new_version\[\/B\]+\[B\]$new_version\[\/B\]\n- $note+" addons.xml
          fi
        done

        # Adding updated plugin package and addon.xml from watchnixtoons2 repo
        cd plugin.video.watchnixtoons2${branch}
        wget "https://github.com/christianhaitian/plugin.video.watchnixtoons2/raw/${branch4repo}/plugin.video.watchnixtoons2${branch}-${new_version}.zip"
        rm -f addon.xml
        wget "https://github.com/christianhaitian/plugin.video.watchnixtoons2/raw/${branch4repo}/addon.xml"
        cd ..

        # Set new md5
        cur_md5=$(cat addons.xml.md5)
        new_md5=$(echo $cur_md5 | awk '{print $1+1}')
        echo $new_md5 > addons.xml.md5

        # Setup, commit and push plugin, updated addons.xml, and updated md5
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add plugin.video.watchnixtoons2${branch}/plugin.video.watchnixtoons2${branch}-${new_version}.zip 
        git add plugin.video.watchnixtoons2${branch}/addon.xml addons.xml*
        git commit -m "Add plugin.video.watchnixtoons2${branch}-${new_version}.zip to repo"
        git push
      env:
        cur_version: ${{ env.cur_version }}
        new_version: ${{ env.new_version }}
        branch: ${{ env.branch }}
        branch4repo: ${{ env.branch4repo }}
